<section class="p-lg-0">
   <div class="container">
      <div class="row align-items-center p-7">
          <div class="col-lg-5 mt-6 mt-lg-0">
            <img class="" height="350" src="<?= $sbs['config']['site_url'] ?>layout/assets/images/404.png" alt="">
         </div>
         <div class="col-lg-5 d-flex align-items-center">
            <div>
               <h1>404 Error</h1>
               <h3 class="my-3">Oops! Page Not Found</h3>
               <h6 class="mb-6">You’re either misspelling the URL
                  or requesting a page that's no longer here.
               </h6>
               <a class="btn btn-theme" href="<?= $sbs['config']['site_url'] ?>"><span>Back To Home Page</span></a>
            </div>
         </div>
       
      </div>
   </div>
</section>