 <?php
$orders = get_data("my_orders", "WHERE o_business_id = '" . $sbs['bss']['business_id'] . "'");
$bill_no = __secure($_GET['bill']);
if (empty($bill_no)) {
    header("location: index.php?page=Orders");
}
$myOrder = myOrders($sbs['bss']['business_id'], $bill_no);
$error = "";
$total = 0;
foreach ($myOrder as $order) {
    $itemData = single_item("items", "WHERE item_id = '" . $order['item_id'] . "'");
    $total += $itemData['item_price'] * $order['quantity'];
}

?>
 <!--begin::Content-->
                <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
                    <!--begin::Container-->
                    <div class="container-xxl" id="kt_content_container">
                            <div class="text-center mb-18">
                            <!--begin::Title-->
                            <h3 class="fs-2hx text-dark mb-6"><?= $sbs['bss']['b_name'] ?></h3>
                            <!--end::Title-->
                            <!--begin::Text-->
                            <div class="fs-5 text-dark fw-bold">Edit Sales Order<br> Bill No. <?=$bill_no?>
                            </div>
                            <!--end::Text-->

                        </div>
                        <!--begin::Order details page-->
                        <div class="d-flex flex-column gap-7 gap-lg-10">
                            <div class="d-flex flex-wrap flex-stack gap-5 gap-lg-10">
                                <!--begin:::Tabs-->
                                <ul class="nav nav-custom nav-tabs nav-line-tabs nav-line-tabs-2x border-0 fs-4 fw-bold mb-lg-n2 me-auto">
                                    <!--begin:::Tab item-->
                                    <li class="nav-item">
                                        <a class="nav-link text-active-primary pb-4 active" data-bs-toggle="tab" href="#kt_ecommerce_sales_order_summary">Order Summary</a>
                                    </li>
                                    <!--end:::Tab item-->
                                    <!--begin:::Tab item-->
                                   <!--  <li class="nav-item">
                                        <a class="nav-link text-active-primary pb-4" data-bs-toggle="tab" href="#kt_ecommerce_sales_order_history">Order History</a>
                                    </li> -->
                                    <!--end:::Tab item-->
                                </ul>
                                <!--end:::Tabs-->
                                <!--begin::Button-->
                                <a href="listing.html" class="btn btn-icon btn-light-primary btn-sm ms-auto me-lg-n7">
                                    <!--begin::Svg Icon | path: icons/duotune/arrows/arr074.svg-->
                                    <span class="svg-icon svg-icon-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                            <path d="M11.2657 11.4343L15.45 7.25C15.8642 6.83579 15.8642 6.16421 15.45 5.75C15.0358 5.33579 14.3642 5.33579 13.95 5.75L8.40712 11.2929C8.01659 11.6834 8.01659 12.3166 8.40712 12.7071L13.95 18.25C14.3642 18.6642 15.0358 18.6642 15.45 18.25C15.8642 17.8358 15.8642 17.1642 15.45 16.75L11.2657 12.5657C10.9533 12.2533 10.9533 11.7467 11.2657 11.4343Z" fill="currentColor" />
                                        </svg>
                                    </span>
                                    <!--end::Svg Icon-->
                                </a>
                    
                                <!--end::Button-->
                                <!--begin::Button-->
                                <a href="index.php?page=addOrder" class="btn btn-light-primary btn-sm">Add New Order</a>
                                <!--end::Button-->
                            </div>
                            <!--begin::Order summary-->

                            <!--end::Order summary-->
                            <!--begin::Tab content-->
                            <div class="tab-content">
                                <!--begin::Tab pane-->
                                <div class="tab-pane fade show active" id="kt_ecommerce_sales_order_summary" role="tab-panel">
                                    <!--begin::Orders-->
                                    <div class="d-flex flex-column gap-7 gap-lg-10">

                                        <!--begin::Product List-->
                                        <div class="card card-flush py-4 flex-row-fluid overflow-hidden">
                                            <!--begin::Card header-->
                                            <div class="card-header">
                                                <div class="card-title">
                                                    <h2>Bill No. #<?= $bill_no ?></h2>
                                                </div>
                                            </div>
                                            <!--end::Card header-->
                                            <!--begin::Card body-->
                                            <div class="card-body pt-0">
                                                <div class="table-responsive">
                                                    <!--begin::Table-->
                                                    <table class="table align-middle table-row-dashed fs-6 gy-5 mb-0">
                                                        <!--begin::Table head-->
                                                        <thead>
                                                            <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                                                                <th class="min-w-10px">S/No.</th>
                                                                <th class="min-w-100px">Product</th>

                                                                <th class="min-w-70px">Qty</th>
                                                                <th class="min-w-100px text-end">Unit Price</th>
                                                                <th class="min-w-100px text-end">Total</th>
                                                                <th class="min-w-100px text-end">Discount</th>
                                                                <th class="min-w-100px text-end">Total Total</th>
                                                                <th class="min-w-100px text-end">Actions</th>
                                                            </tr>
                                                        </thead>
                                                        <!--end::Table head-->
                                                        <!--begin::Table body-->
                                                        <tbody class="fw-bold text-gray-600">
                                                            <!--begin::Products-->
                                                            <?php
                                                            $num = 0;
                                                            $total = 0;
                                                            foreach ($myOrder as $order) :
                                                                $itemData = single_item("items", "WHERE item_id = '" . $order['item_id'] . "'");
                                                                $total += ($itemData['item_price'] * $order['quantity']) - $order['discount'];
                                                                $dis = 0;
                                                                if (!empty($order['discount'])) {
                                                                    $dis = $order['discount'];
                                                                }
                                                            ?>
                                                                <tr>
                                                                    <!--begin::Product-->
                                                                    <td><?= $num += 1 ?></td>
                                                                    <td><?= $itemData['item_name'] ?></td>
                                                                    <!--end::Product-->
                                                                    <!--begin::SKU-->
                                                                    <!--end::SKU-->
                                                                    <!--begin::Quantity-->
                                                                    <td class=""><?= $order['quantity'] ?></td>
                                                                    <!--end::Quantity-->
                                                                    <!--begin::Price-->
                                                                    <td class="text-end">UGX: <?= number_format($itemData['item_price'], 0, '', ','); ?></td>
                                                                    <!--end::Price-->
                                                                    <!--begin::Total-->
                                                                    <td class="text-end">UGX: <?= number_format($itemData['item_price'] * $order['quantity'], 0, '', ','); ?></td>
                                                                     <td class="text-end">UGX: <?= number_format($order['discount'], 0, '', ','); ?></td>
                                                                      <td class="text-end">UGX: <?= number_format((($itemData['item_price'] * $order['quantity']) - $dis), 0, '', ','); ?></td>
                                                                    <!--end::Total-->
                                                <td class="text-end">
                                                       
                                                                    <a href="#" class="btn btn-sm btn-light btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">Edit Qty
                                                        
                                                    </a>
                                                    <!--begin::Menu-->
                                                    <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-225px " data-kt-menu="true">
                                                        <form  class="edit_order_qty" method="post">
                                                            <input type="text" value="<?= $order['id'] ?>" name="id" hidden />
                                                            <input type="text" value="<?= $order['discount'] ?>" name="disc" hidden />
                                                            <input type="text" value="<?= $order['quantity'] ?>" name="old_qty" hidden />
                                                             <input type="text" value="<?= $order['item_id'] ?>" name="item_id" hidden />

                                                            <div class="d-flex flex-column mb-2 fv-row">
                                                                <input class="form-control form-control-solid" type="text" value="<?= $order['quantity'] ?>" name="qty" />
                                                                <!--end::Input-->
                                                            </div>
        
                                                            <div class="modal-footer flex-center">

                                                                <!--begin::Button-->
                                                                <button type="submit" name="editOrder_qty" id="kt_modal_new_address_submit" class="btn btn-primary">
                                                                    <span class="indicator-label">Edit</span>

                                                                </button>
                                                                <!--end::Button-->
                                                            </div>
                                                        </form>
                                                    </div>
                                                       <a class="btn btn-sm btn-light btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
                                                        <span class='delete' data-id='<?= $order['id']; ?>'>Delete</span>
                                                    </a>
                                                                    </td>
                                                                    
                                                                </tr>
                                                            <?php endforeach; ?>
                                                            <!--end::Products-->
                                                            <!--begin::Subtotal-->
                                                            <tr>
                                                                <td colspan="4" class="text-end">Subtotal</td>
                                                                <td class="text-end subto">UGX: <?= number_format($total, 0, '', ','); ?></td>
                                                            </tr>
                                                            <!--end::Subtotal-->
                                                            <!--begin::VAT-->
                                                            <tr>
                                                                <td colspan="4" class="text-end">VAT (0%)</td>
                                                                <td class="text-end">UGX :0</td>
                                                            </tr>
                                                            <!--end::VAT-->
                                                            <!--begin::Shipping-->
                                                            <!-- <tr>
                                                                <td colspan="4" class="text-end">Shipping Rate</td>
                                                                <td class="text-end">$5.00</td>
                                                            </tr> -->
                                                            <!--end::Shipping-->
                                                            <!--begin::Grand total-->
                                                            <tr>
                                                                <td colspan="4" class="fs-3 text-dark text-end ">Grand Total</td>
                                                                <td class="text-dark fs-3 fw-boldest text-end subto">UGX: <?= number_format($total, 0, '', ','); ?></td>
                                                            </tr>
                                                            <!--end::Grand total-->
                                                        </tbody>
                                                        <!--end::Table head-->
                                                    </table>
                                                    <!--end::Table-->
                                                </div>
                                            </div>
                                            <!--end::Card body-->
                                        </div>
                                        <!--end::Product List-->
                                     
                                    </div>
                                    <!--end::Orders-->
                                     <div class="d-flex flex-column flex-xl-row gap-7 gap-lg-10">
                                            <!--begin::Payment address-->
                                            <div class="card card-flush py-4 flex-row-fluid overflow-hidden">
                                                <!--begin::Background-->
                                                <div class="position-absolute top-0 end-0 opacity-10 pe-none text-end">
                                                    <img src="../../../assets/media/icons/duotune/ecommerce/ecm001.svg" class="w-175px" />
                                                </div>
                                                <!--end::Background-->
                                                <!--begin::Card header-->
                                                <div class="card-header">
                                                    <div class="card-title">
                                                        <h2>Clear Payment</h2>
                                                    </div>
                                                </div>
                                                <!--end::Card header-->
                                                <!--begin::Card body-->
                                                <div class="card-body pt-0">
                                                    <?php
                                                    if ($error == "pay_fail") {
                                                        echo $msg;
                                                    }
                                                    ?>
                                                    <centre>
                                                        <form class="form-control pay">
                                                             <input type="text" name="bill" value="<?=$bill_no ?>" hidden>
                                                            <!--begin::Input group-->
                                                            <div class="d-flex flex-column mb-3 fv-row">
                                                                <!--begin::Label-->
                                                                <label class="required fs-5 fw-bold mb-2">Enter Amount Recevied</label>
                                                                <!--end::Label-->
                                                                <!--begin::Input-->
                                                                <input class="form-control form-control-solid" type="number" placeholder="Amount Received From Customer" name="amount" />
                                                                <!--end::Input-->
                                                            </div>
                                                            <!--end::Input group-->
                                                            <!--end::Order details-->
                                                            <div class="d-flex flex-column mb-3 fv-row">

                                                                <!--begin::Button-->
                                                                <button type="submit" name="confirmPay" class="btn btn-primary">
                                                                    <span class="indicator-label">confirm Payment</span>
                                                                    <span class="indicator-progress">Please wait...
                                                                        <span class="spinner-border spinner-border-sm align-middle ms-5"></span></span>
                                                                </button>
                                                                <!--end::Button-->
                                                            </div>
                                                        </form>
                                                    </centre>
                                                </div>
                                                <!--end::Card body-->
                                            </div>
                                            <!--end::Payment address-->
                                            <!--begin::Shipping address-->

                                            <!--end::Shipping address-->
                                        </div>
                                </div>
                                <!--end::Tab pane-->
                                <!--begin::Tab pane-->
                                <div class="tab-pane fade" id="kt_ecommerce_sales_order_history" role="tab-panel">
                                    <!--begin::Orders-->
                                    <div class="d-flex flex-column gap-7 gap-lg-10">
                                        <!--begin::Order history-->
                                        <div class="card card-flush py-4 flex-row-fluid">
                                            <!--begin::Card header-->
                                            <div class="card-header">
                                                <div class="card-title">
                                                    <!-- <h2>Order History</h2> -->
                                                </div>
                                            </div>
                                            <!--end::Card header-->
                                            <!--begin::Card body-->
                                            <div class="card-body pt-0">
                                                <div class="table-responsive">
                                                    <!--begin::Table-->
                                                    <table class="table align-middle table-row-dashed fs-6 gy-5 mb-0">
                                                        <!--begin::Table head-->
                                                        <thead>
                                                            <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                                                                <th class="min-w-100px">Date Added</th>
                                                                <th class="min-w-175px">Comment</th>
                                                                <th class="min-w-70px">Order Status</th>
                                                                <th class="min-w-100px">Customer Notifed</th>
                                                            </tr>
                                                        </thead>
                                                        <!--end::Table head-->
                                                        <!--begin::Table body-->
                                                        <tbody class="fw-bold text-gray-600">
                                                            <tr>
                                                                <!--begin::Date-->
                                                                <td>03/06/2022</td>
                                                                <!--end::Date-->
                                                                <!--begin::Comment-->
                                                                <td>Order completed</td>
                                                                <!--end::Comment-->
                                                                <!--begin::Status-->
                                                                <td>
                                                                    <!--begin::Badges-->
                                                                    <div class="badge badge-light-success">Completed</div>
                                                                    <!--end::Badges-->
                                                                </td>
                                                                <!--end::Status-->
                                                                <!--begin::Customer Notified-->
                                                                <td>No</td>
                                                                <!--end::Customer Notified-->
                                                            </tr>
                                                            <tr>
                                                                <!--begin::Date-->
                                                                <td>02/06/2022</td>
                                                                <!--end::Date-->
                                                                <!--begin::Comment-->
                                                                <td>Order received by customer</td>
                                                                <!--end::Comment-->
                                                                <!--begin::Status-->
                                                                <td>
                                                                    <!--begin::Badges-->
                                                                    <div class="badge badge-light-success">Delivered</div>
                                                                    <!--end::Badges-->
                                                                </td>
                                                                <!--end::Status-->
                                                                <!--begin::Customer Notified-->
                                                                <td>Yes</td>
                                                                <!--end::Customer Notified-->
                                                            </tr>
                                                            <tr>
                                                                <!--begin::Date-->
                                                                <td>01/06/2022</td>
                                                                <!--end::Date-->
                                                                <!--begin::Comment-->
                                                                <td>Order shipped from warehouse</td>
                                                                <!--end::Comment-->
                                                                <!--begin::Status-->
                                                                <td>
                                                                    <!--begin::Badges-->
                                                                    <div class="badge badge-light-primary">Delivering</div>
                                                                    <!--end::Badges-->
                                                                </td>
                                                                <!--end::Status-->
                                                                <!--begin::Customer Notified-->
                                                                <td>Yes</td>
                                                                <!--end::Customer Notified-->
                                                            </tr>
                                                            <tr>
                                                                <!--begin::Date-->
                                                                <td>31/05/2022</td>
                                                                <!--end::Date-->
                                                                <!--begin::Comment-->
                                                                <td>Payment received</td>
                                                                <!--end::Comment-->
                                                                <!--begin::Status-->
                                                                <td>
                                                                    <!--begin::Badges-->
                                                                    <div class="badge badge-light-primary">Processing</div>
                                                                    <!--end::Badges-->
                                                                </td>
                                                                <!--end::Status-->
                                                                <!--begin::Customer Notified-->
                                                                <td>No</td>
                                                                <!--end::Customer Notified-->
                                                            </tr>
                                                            <tr>
                                                                <!--begin::Date-->
                                                                <td>30/05/2022</td>
                                                                <!--end::Date-->
                                                                <!--begin::Comment-->
                                                                <td>Pending payment</td>
                                                                <!--end::Comment-->
                                                                <!--begin::Status-->
                                                                <td>
                                                                    <!--begin::Badges-->
                                                                    <div class="badge badge-light-warning">Pending</div>
                                                                    <!--end::Badges-->
                                                                </td>
                                                                <!--end::Status-->
                                                                <!--begin::Customer Notified-->
                                                                <td>No</td>
                                                                <!--end::Customer Notified-->
                                                            </tr>
                                                            <tr>
                                                                <!--begin::Date-->
                                                                <td>29/05/2022</td>
                                                                <!--end::Date-->
                                                                <!--begin::Comment-->
                                                                <td>Payment method updated</td>
                                                                <!--end::Comment-->
                                                                <!--begin::Status-->
                                                                <td>
                                                                    <!--begin::Badges-->
                                                                    <div class="badge badge-light-warning">Pending</div>
                                                                    <!--end::Badges-->
                                                                </td>
                                                                <!--end::Status-->
                                                                <!--begin::Customer Notified-->
                                                                <td>No</td>
                                                                <!--end::Customer Notified-->
                                                            </tr>
                                                            <tr>
                                                                <!--begin::Date-->
                                                                <td>28/05/2022</td>
                                                                <!--end::Date-->
                                                                <!--begin::Comment-->
                                                                <td>Payment method expired</td>
                                                                <!--end::Comment-->
                                                                <!--begin::Status-->
                                                                <td>
                                                                    <!--begin::Badges-->
                                                                    <div class="badge badge-light-danger">Failed</div>
                                                                    <!--end::Badges-->
                                                                </td>
                                                                <!--end::Status-->
                                                                <!--begin::Customer Notified-->
                                                                <td>Yes</td>
                                                                <!--end::Customer Notified-->
                                                            </tr>
                                                            <tr>
                                                                <!--begin::Date-->
                                                                <td>27/05/2022</td>
                                                                <!--end::Date-->
                                                                <!--begin::Comment-->
                                                                <td>Pending payment</td>
                                                                <!--end::Comment-->
                                                                <!--begin::Status-->
                                                                <td>
                                                                    <!--begin::Badges-->
                                                                    <div class="badge badge-light-warning">Pending</div>
                                                                    <!--end::Badges-->
                                                                </td>
                                                                <!--end::Status-->
                                                                <!--begin::Customer Notified-->
                                                                <td>No</td>
                                                                <!--end::Customer Notified-->
                                                            </tr>
                                                            <tr>
                                                                <!--begin::Date-->
                                                                <td>26/05/2022</td>
                                                                <!--end::Date-->
                                                                <!--begin::Comment-->
                                                                <td>Order received</td>
                                                                <!--end::Comment-->
                                                                <!--begin::Status-->
                                                                <td>
                                                                    <!--begin::Badges-->
                                                                    <div class="badge badge-light-warning">Pending</div>
                                                                    <!--end::Badges-->
                                                                </td>
                                                                <!--end::Status-->
                                                                <!--begin::Customer Notified-->
                                                                <td>Yes</td>
                                                                <!--end::Customer Notified-->
                                                            </tr>
                                                        </tbody>
                                                        <!--end::Table head-->
                                                    </table>
                                                    <!--end::Table-->
                                                </div>
                                            </div>
                                            <!--end::Card body-->
                                        </div>
                                        <!--end::Order history-->
                                        <!--begin::Order data-->
                                        <div class="card card-flush py-4 flex-row-fluid">
                                            <!--begin::Card header-->
                                            <div class="card-header">
                                                <div class="card-title">
                                                    <h2>Order Data</h2>
                                                </div>
                                            </div>
                                            <!--end::Card header-->
                                            <!--begin::Card body-->
                                            <div class="card-body pt-0">
                                                <div class="table-responsive">
                                                    <!--begin::Table-->
                                                    <table class="table align-middle table-row-bordered mb-0 fs-6 gy-5">
                                                        <!--begin::Table body-->
                                                        <tbody class="fw-bold text-gray-600">
                                                            <!--begin::IP address-->
                                                            <tr>
                                                                <td class="text-muted">IP Address</td>
                                                                <td class="fw-bolder text-end">172.68.221.26</td>
                                                            </tr>
                                                            <!--end::IP address-->
                                                            <!--begin::Forwarded IP-->
                                                            <tr>
                                                                <td class="text-muted">Forwarded IP</td>
                                                                <td class="fw-bolder text-end">89.201.163.49</td>
                                                            </tr>
                                                            <!--end::Forwarded IP-->
                                                            <!--begin::User agent-->
                                                            <tr>
                                                                <td class="text-muted">User Agent</td>
                                                                <td class="fw-bolder text-end">Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36</td>
                                                            </tr>
                                                            <!--end::User agent-->
                                                            <!--begin::Accept language-->
                                                            <tr>
                                                                <td class="text-muted">Accept Language</td>
                                                                <td class="fw-bolder text-end">en-GB,en-US;q=0.9,en;q=0.8</td>
                                                            </tr>
                                                            <!--end::Accept language-->
                                                        </tbody>
                                                        <!--end::Table body-->
                                                    </table>
                                                    <!--end::Table-->
                                                </div>
                                            </div>
                                            <!--end::Card body-->
                                        </div>
                                        <!--end::Order data-->
                                    </div>
                                    <!--end::Orders-->
                                </div>
                                <!--end::Tab pane-->
                            </div>
                            <!--end::Tab content-->
                        </div>
                        <!--end::Order details page-->
                    </div>
                    <!--end::Container-->
                </div>
                <!--end::Content-->
                <script type="text/javascript">
    $(document).ready(function() {
        $('.edit_order_qty').on('submit', function(e) {
            e.preventDefault();
            $.ajax({
                url: request()+'?f=orders&s=edit_order_qty&bill_no=<?=$bill_no?>',
                method: 'POST',
                data: $(this).serialize(),
                beforesend: function() {

                },
                success: function(response) {
                    console.log(response);
                    //e.removeAttribute("data-kt-indicator");

                    if (response.status == 200) {
                        Swal.fire({
                            text: response.message,
                            icon: "success",
                            buttonsStyling: !1,
                            confirmButtonText: "Redirecting You",
                            customClass: {
                                confirmButton: "btn btn-primary"
                            }
                        });
                        setTimeout(function() {
                            window.location.href = response.url;
                        }, 2e3);

                    } else {
                        Swal.fire({
                            text: response.message,
                            icon: "warning",
                            buttonsStyling: !1,
                            confirmButtonText: "Try Again!",
                            customClass: {
                                confirmButton: "btn btn-danger"
                            }
                        });
                    }
                }
            });
        });

    })
       $(document).ready(function() {

        // Delete 
        $('.delete').click(function() {
            var el = this;

            // Delete id
            var deleteid = $(this).data('id');

            var confirmalert = confirm("Are you sure ?");
            if (confirmalert == true) {
                // AJAX Request
                $.ajax({
                    url: request()+'?f=orders&s=delOrder_item&bill_no=<?=$bill_no?>',
                    type: 'POST',
                    data: {
                        id: deleteid
                    },
                    success: function(response) {

                        if (response.status == 200) {
                             $('.subto').html(response.total);
                             $('.subto').removeClass('disabled');
                            // Remove row from HTML Table
                            $(el).closest('tr').css('background', 'tomato');
                            $(el).closest('tr').fadeOut(800, function() {
                                $(this).remove();
                            });
                        } else {
                            alert(response.message);
                        }

                    }
                });
            }

        });

    });
    $(document).ready(function() {
        $('.pay').on('submit', function(e) {
            e.preventDefault();
            $.ajax({
                url: request()+'?f=orders&s=pay',
                method: 'POST',
                data: $(this).serialize(),
                beforesend: function() {

                },
                success: function(response) {
                    console.log(response);
                    //e.removeAttribute("data-kt-indicator");

                    if (response.status == 200) {
                        Swal.fire({
                            text: response.bill_status,
                            icon: "success",
                            buttonsStyling: !1,
                            confirmButtonText: "Redirecting You To Receipt",
                            customClass: {
                                confirmButton: "btn btn-primary"
                            }
                        });
                        setTimeout(function() {
                            window.location.href = response.url;
                        }, 2e3);
                        $('.orders').html(response.message);
                        $('.total').html(response.total);
                        $total = response.total;
                    } else {
                        Swal.fire({
                            text: response.message,
                            icon: "warning",
                            buttonsStyling: !1,
                            confirmButtonText: "Try Again!",
                            customClass: {
                                confirmButton: "btn btn-danger"
                            }
                        });
                    }
                }
            });
        });
    })
</script>