  <?php
$today = getCurrentDate();
$todayTime = getCurrentDateOnly();
if (isset($_GET['date'])) {
    $todayTime = __secure($_GET['date']);
}
$day1 = $todayTime . ' 00:00:00';
$day2 = $todayTime . ' 23:59:59';
$totalOrders = 0;
$report = "Procedures Recorded By " . $sbs['user']['firstname'] . " " . $sbs['user']['lastname'] . "  (Cashier)";
$orders = getProcedureBetweenDaysByCashier($day1, $day2, $sbs['bss']['business_id'], $sbs['user']['user_id']);
if (empty($sbs['user']['is_cashier'])) {
   $report = "Procedures";
   $orders = getTodaysData("med_procedure", "business_id", $sbs['bss']['business_id'], "created", $todayTime);
}
foreach ($orders as $order) {
    
    $totalOrders += $order['amount'];
}
$all_users = get_data("users");
?>

  <!--begin::Content-->
                <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
                    <!--begin::Container-->
                    <div class="container-xxl" id="kt_content_container">
                        <div class="text-center mb-18">
                            <!--begin::Title-->
                            <h3 class="fs-2hx text-dark mb-6"><?= $sbs['bss']['b_name'] ?></h3>
                            <!--end::Title-->
                            <!--begin::Text-->
                             <div class="fs-5 text-dark fw-bold"><?= $report ?>
                                <br /><?php if (isset($_GET['date'])) {
                                    echo 'As At : ' . date('d/m/Y', strtotime(date(__secure($_GET['date'])))) . '<br />Total Amounts =.UGX:  ' . number_format($totalOrders, 0, '', ','); 
                                }else{

                                echo 'As At : ' . date('d/m/Y g:iA', strtotime(date('Y-m-d g:ia'))) . '<br />Total Amounts =.UGX:  ' . number_format($totalOrders, 0, '', ','); 
                            } ?><br />
                            </div>
                            <!--end::Text-->

                        </div>
                        <!--begin::Products-->
                        <div class="card card-flush">
                            <!--begin::Card header-->
                            <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                                <!--begin::Card title-->
                                <div class="card-title">
                                    <!--begin::Search-->
                                    <div class="d-flex align-items-center position-relative my-1">
                                        <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                                        <span class="svg-icon svg-icon-1 position-absolute ms-4">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                                                <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
                                            </svg>
                                        </span>
                                        <!--end::Svg Icon-->
                                        <input type="text" data-kt-ecommerce-order-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Search Procedure" />
                                    </div>
                                    <!--end::Search-->

                                    <!--begin::Export buttons-->
                                    <div id="kt_ecommerce_report_sales_export" class="d-none"></div>
                                    <!--end::Export buttons-->
                                </div>
                                <?php if (empty($sbs['user']['is_cashier'])) { ?>
                                    <!--begin::Actions-->
                                            <div class="d-flex my-4">


                                                <!--begin::Menu-->
                                                <div class="me-0">
                                                    <button class="btn btn-sm btn-icon btn-bg-light btn-active-color-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
                                                        <i class="bi bi-three-dots fs-3"></i>
                                                    </button>
                                                    <!--begin::Menu 3-->
                                                    <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg-light-primary fw-bold w-200px py-3" data-kt-menu="true">
                                                        <!--begin::Heading-->
                                                        <div class="menu-item px-3">
                                                            <div class="menu-content text-muted pb-2 px-3 fs-7 text-uppercase">Check Previous Procedures</div>
                                                        </div>
                                                        <!--end::Heading-->
                                                        <form class="form checkPrev">
                                                        <!--begin::Menu item-->
                                                          <div class="d-flex flex-column mb-5 fv-row">
                                                            <!--begin::Label-->
                                                            <!--end::Label-->
                                                            <!--begin::Input-->
                                                            <input class="form-control" type="date" name="date" />
                                                            <!--end::Input-->

                                                        </div>
                                                        <div class="menu-item px-3">
                                                            <button type="submit" class="btn btn-light-primary">Check Procedures</button>
                                                          
                                                        </div>
                                                        </form>
                                                        <!--end::Menu item-->

                                                    </div>
                                                    <!--end::Menu 3-->
                                                </div>
                                                <!--end::Menu-->
                                            </div>
                                <!--end::Card title-->
                               <?php } ?>
                                <!--end::Card title-->

                                <!--begin::Card toolbar-->
                                <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
                                    <!--begin::Daterangepicker-->
                                    <!--begin::Add product-->
                                    <div class="card-toolbar" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-trigger="hover" title="" data-bs-original-title="click to add New Procedure">
                                    <a data-bs-toggle="modal" data-bs-target="#kt_modal_new_address1" href="index.php?page=addProcedure" class="btn btn-primary">Add Procedure</a>
                                </div>
                                    <!--end::Add product-->
                                    
                                    <!--end::Daterangepicker-->
                                    <!--begin::Export dropdown-->
                                    <button type="button" class="btn btn-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
                                        <!--begin::Svg Icon | path: icons/duotune/arrows/arr078.svg-->
                                        <span class="svg-icon svg-icon-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                <rect opacity="0.3" x="12.75" y="4.25" width="12" height="2" rx="1" transform="rotate(90 12.75 4.25)" fill="currentColor" />
                                                <path d="M12.0573 6.11875L13.5203 7.87435C13.9121 8.34457 14.6232 8.37683 15.056 7.94401C15.4457 7.5543 15.4641 6.92836 15.0979 6.51643L12.4974 3.59084C12.0996 3.14332 11.4004 3.14332 11.0026 3.59084L8.40206 6.51643C8.0359 6.92836 8.0543 7.5543 8.44401 7.94401C8.87683 8.37683 9.58785 8.34458 9.9797 7.87435L11.4427 6.11875C11.6026 5.92684 11.8974 5.92684 12.0573 6.11875Z" fill="currentColor" />
                                                <path d="M18.75 8.25H17.75C17.1977 8.25 16.75 8.69772 16.75 9.25C16.75 9.80228 17.1977 10.25 17.75 10.25C18.3023 10.25 18.75 10.6977 18.75 11.25V18.25C18.75 18.8023 18.3023 19.25 17.75 19.25H5.75C5.19772 19.25 4.75 18.8023 4.75 18.25V11.25C4.75 10.6977 5.19771 10.25 5.75 10.25C6.30229 10.25 6.75 9.80228 6.75 9.25C6.75 8.69772 6.30229 8.25 5.75 8.25H4.75C3.64543 8.25 2.75 9.14543 2.75 10.25V19.25C2.75 20.3546 3.64543 21.25 4.75 21.25H18.75C19.8546 21.25 20.75 20.3546 20.75 19.25V10.25C20.75 9.14543 19.8546 8.25 18.75 8.25Z" fill="#C4C4C4" />
                                            </svg>
                                        </span>
                                        <!--end::Svg Icon-->Export Report
                                    </button>
                                    <!--begin::Menu-->
                                    <div id="kt_ecommerce_report_sales_export_menu" class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-200px py-4" data-kt-menu="true">
                                        <!--begin::Menu item-->
                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3" data-kt-ecommerce-export="copy">Copy to clipboard</a>
                                        </div>
                                        <!--end::Menu item-->
                                        <!--begin::Menu item-->
                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3" data-kt-ecommerce-export="excel">Export as Excel</a>
                                        </div>
                                        <!--end::Menu item-->
                                        <!--begin::Menu item-->
                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3" data-kt-ecommerce-export="csv">Export as CSV</a>
                                        </div>
                                        <!--end::Menu item-->
                                        <!--begin::Menu item-->
                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3" data-kt-ecommerce-export="pdf">Export as PDF</a>
                                        </div>
                                        <!--end::Menu item-->
                                    </div>
                                    <!--end::Menu-->
                                    <!--end::Export dropdown-->
                                </div>
                                <!--end::Card toolbar-->
                            </div>
                            <!--end::Card header-->
                            <!--begin::Card body-->
                            <div class="card-body pt-0">
                                <!--begin::Table-->
                                 <?php if (empty($users_status)) { ?>
                                    <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_ecommerce_report_sales_table">
                                    <!--begin::Table head-->
                                    <thead>
                                        <!--begin::Table row-->
                                        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                                            <th class="min-w-10px">S/No.</th>
                                            <th class="min-w-50px">Date</th>
                                            <th class="min-w-50px">Title</th>
                                            <th class="min-w-50px">Customer Name</th>
                                            <th class="min-w-50px">Amount Charged</th>
                                            <th class="min-w-50px">Status</th>
                                            <th class="min-w-50px">Cashier</th>
                                            <th class="min-w-50px">Action</th>
                                        </tr>
                                        <!--end::Table row-->
                                    </thead>
                                    <!--end::Table head-->
                                    <!--begin::Table body-->
                                    <tbody class="fw-bold text-gray-600">
                                        <!--begin::Table row-->
                                        <?php
                                        $num = 0;
                                        foreach ($orders as $order) :
                                            $one_user = single_item("users", "WHERE user_id = '".$order['cashier_id']."'")

                                        ?>
                                            <tr>
                                                <td><?= $num += 1 ?></td>
                                                <!--begin::Date=-->
                                                <td><?= $order['created'] ?></td>
                                                <!--end::Date=-->
                                                <!--begin::No Orders=-->
                                                <td ><?= $order['title'] ?></td>
                                                <!--end::No Orders=-->
                                                <!--begin::Products sold=-->
                                                <!--end::Products sold=-->
                                                <!--begin::Tax=-->
                                                <td><?= $order['customer_name'] ?></td>
                                                <!--end::Tax=-->
                                                <!--begin::Total=-->
                                                <td >UGX: <?= number_format($order['amount'], 0, '', ','); ?></td>
                                                 <?php if ($order['status'] == 0) { ?>
                                                    <td  data-order="Credit">
                                                        <!--begin::Badges-->
                                                        <div class="badge badge-light-danger">Credit</div>
                                                        <!--end::Badges-->
                                                    </td>
                                                <?php } else { ?>
                                                    <td data-order="Paid">
                                                        <div class="min-w-125px">
                                                            <span class="badge badge-light-success">Paid</span>
                                                        </div>
                                                    </td>

                                                <?php } ?>
                                                <!--end::Total=-->
                                                <td><?= $one_user['firstname']." ".$one_user['lastname'] ?></td>
                                                 <!--begin::Action=-->
                                                <td><a href="index.php?page=procedure_details&id=<?= $order['id'] ?>">View Details</a> </td>
                                                <!--end::Action=-->
                                            </tr>
                                        <?php endforeach; ?>
                                        <!--end::Table row-->

                                        <!--end::Table row-->



                                    </tbody>
                                    <!--end::Table body-->
                                </table>
                                <!--end::Table-->
                                     <?php }else{ ?>
                                        <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_ecommerce_report_sales_table">
                                    <!--begin::Table head-->
                                    <thead>
                                        <!--begin::Table row-->
                                        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                                            <th class="min-w-10px">S/No.</th>
                                            <th class="min-w-50px">Date</th>
                                            <th class="min-w-50px">Title</th>
                                            <th class="min-w-50px">Customer Name</th>
                                            <th class="min-w-50px">Amount Charged</th>
                                            <th class="min-w-50px">Status</th>
                                            <th class="min-w-50px">Cashier</th>
                                            <th class="min-w-50px">Action</th>
                                        </tr>
                                        <!--end::Table row-->
                                    </thead>
                                    <!--end::Table head-->
                                    <!--begin::Table body-->
                                    <tbody class="fw-bold text-gray-600">
                                        <!--begin::Table row-->
                                        <?php
                                        $num = 0;
                                        foreach ($orders as $order) :
                                          
                                        ?>
                                            <tr>
                                                  <td><?= $num += 1 ?></td>
                                                <!--begin::Date=-->
                                                <td><?= $order['created'] ?></td>
                                                <!--end::Date=-->
                                                <!--begin::No Orders=-->
                                                <td ><?= $order['title'] ?></td>
                                                <!--end::No Orders=-->
                                                <!--begin::Products sold=-->
                                                <!--end::Products sold=-->
                                                <!--begin::Tax=-->
                                                <td><?= $order['customer_name'] ?></td>
                                                <!--end::Tax=-->
                                                <!--begin::Total=-->
                                                <td >UGX: <?= number_format($order['amount'], 0, '', ','); ?></td>
                                                 <?php if ($order['status'] == 0) { ?>
                                                    <td  data-order="Credit">
                                                        <!--begin::Badges-->
                                                        <div class="badge badge-light-danger">Credit</div>
                                                        <!--end::Badges-->
                                                    </td>
                                                <?php } else { ?>
                                                    <td data-order="Paid">
                                                        <div class="min-w-125px">
                                                            <span class="badge badge-light-success">Paid</span>
                                                        </div>
                                                    </td>

                                                <?php } ?>
                                                <!--end::Total=-->
                                                <td><?= $sbs['user']['firstname']." ".$sbs['user']['lastname'] ?></td>
                                                 <!--begin::Action=-->
                                                <td><a href="index.php?page=procedure_details&id=<?= $order['id'] ?>">View Details</a> </td>
                                                <!--end::Action=-->
                                            </tr>
                                        <?php endforeach; ?>
                                        <!--end::Table row-->

                                        <!--end::Table row-->



                                    </tbody>
                                    <!--end::Table body-->
                                </table>
                                <!--end::Table-->

                                         <?php } ?>
                                
                            </div>
                            <!--end::Card body-->
                        </div>
                        <!--end::Products-->
                    </div>
                    <!--end::Container-->
                </div>
                <!--end::Content-->
                
    <!--end::Global Javascript Bundle-->
      <!--begin::Modal - New Address-->
    <div class="modal fade" id="kt_modal_new_address1" tabindex="-1" aria-hidden="true">
        <!--begin::Modal dialog-->
        <div class="modal-dialog modal-dialog-centered mw-650px">
            <!--begin::Modal content-->
            <div class="modal-content">
                <!--begin::Form-->
                <form class="form" id="addBrand">
                    <!--begin::Modal header-->
                    <div class="modal-header" id="kt_modal_new_address_header">
                        <!--begin::Modal title-->
                        <h2>Record Procedure</h2>
                        <!--end::Modal title-->
                        <!--begin::Close-->
                        <div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
                            <!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
                            <span class="svg-icon svg-icon-1">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                    <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor" />
                                    <rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="currentColor" />
                                </svg>
                            </span>
                            <!--end::Svg Icon-->
                        </div>
                        <!--end::Close-->
                    </div>
                    <!--end::Modal header-->
                    <!--begin::Modal body-->
                    <div class="modal-body py-10 px-lg-17">
                        <!--begin::Scroll-->
                        <div class="scroll-y me-n7 pe-7" id="kt_modal_new_address_scroll" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_new_address_header" data-kt-scroll-wrappers="#kt_modal_new_address_scroll" data-kt-scroll-offset="300px">
                            <!--begin::Notice-->
                            <!--begin::Notice-->
                            <div class="notice d-flex bg-light-warning rounded border-warning border border-dashed mb-9 p-6">
                                <!--begin::Icon-->
                                <!--begin::Svg Icon | path: icons/duotune/general/gen044.svg-->
                                Thank You For Choosing SBS, Please Record Your Procedure
                                <!--end::Svg Icon-->
                                <!--end::Icon-->
                            </div>
                            <!--end::Notice-->
                            <!--end::Notice-->

                            <!--end::Input group-->
                            <!--begin::Input group-->
                            <!--end::Input group-->
                            <!--begin::Input group-->
                            <div class="d-flex flex-column mb-5 fv-row">
                                <!--begin::Label-->
                                <label class="required fs-5 fw-bold mb-2">Custome Names</label>
                                <!--end::Label-->
                                <!--begin::Input-->
                                <input class="form-control form-control-solid" type="text" placeholder="Customer Names" name="customer_name" />
                                <!--end::Input-->
                            </div>
                             <div class="d-flex flex-column mb-5 fv-row">
                                <!--begin::Label-->
                                <label class="required fs-5 fw-bold mb-2">Procedure Title</label>
                                <!--end::Label-->
                                <!--begin::Input-->
                                <input class="form-control form-control-solid" type="text" placeholder="Procedure Title / Name" name="title" />
                                <!--end::Input-->
                            </div>
                             <div class="d-flex flex-column mb-5 fv-row">
                                <!--begin::Label-->
                                <label class="required fs-5 fw-bold mb-2">Description</label>
                                <!--end::Label-->
                                <!--begin::Input-->
                                <textarea type="text" name="description" class="form-control mt-6 shadow-outline-none rounded py-10 px-5 text-[25px] font-bold" placeholder="Enter Procedure Description here" value=""></textarea>
                                <!--end::Input-->
                            </div>
                              <div class="d-flex flex-column mb-5 fv-row">
                                <!--begin::Label-->
                                <label class="required fs-5 fw-bold mb-2">Amount To Be Charged</label>
                                <!--end::Label-->
                                <!--begin::Input-->
                                <input class="form-control form-control-solid" type="text" placeholder="Amount" name="amount" />
                                <!--end::Input-->
                            </div>
                            <!--end::Input group-->
                            <!--begin::Input group-->

                            <!--end::Input group-->

                        </div>
                        <!--end::Scroll-->
                    </div>
                    <!--end::Modal body-->
                    <!--begin::Modal footer-->
                    <div class="modal-footer flex-center">
                        <!--begin::Button-->
                        <button type="reset" id="kt_modal_new_address_cancel" class="btn btn-light me-3">Discard</button>
                        <!--end::Button-->
                        <!--begin::Button-->
                        <button type="submit" name="addProduct" id="kt_modal_new_address_submit" class="btn btn-primary">
                            <span class="indicator-label">Record Procedure</span>
                            <span class="indicator-progress">Please wait...
                                <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                        </button>
                        <!--end::Button-->
                    </div>
                    <!--end::Modal footer-->
                </form>
                <!--end::Form-->
            </div>
        </div>
    </div>
    <!--end::Modal - New Address-->
<script type="text/javascript">
    "use strict";



$(document).ready(function() {
        $('#addBrand').on('submit', function(e) {
            e.preventDefault();

            $.ajax({
                url: request()+'?f=procedure&s=add',
                method: 'POST',
                data: $(this).serialize(),
                beforesend: function() {

                },
                success: function(response) {
                    console.log(response);
                    //e.removeAttribute("data-kt-indicator");

                    if (response.status == 200) {
                        Swal.fire({
                            text: response.message,
                            icon: "success",
                            buttonsStyling: !1,
                            confirmButtonText: "Redirecting You",
                            customClass: {
                                confirmButton: "btn btn-primary"
                            }
                        });
                        setTimeout(function() {
                            location.reload();
                        }, 2e3);
                    } else {
                        Swal.fire({
                            text: response.message,
                            icon: "warning",
                            buttonsStyling: !1,
                            confirmButtonText: "Try Again!",
                            customClass: {
                                confirmButton: "btn btn-danger"
                            }
                        });
                    }
                }
            });
        });

    })
// Class definition
var KTAppEcommerceReportSales = function () {
    // Shared variables
    var table;
    var datatable;

    // Private functions
    var initDatatable = function () {
        // Set date data order
        const tableRows = table.querySelectorAll('tbody tr');

        tableRows.forEach(row => {
            const dateRow = row.querySelectorAll('td');
            const realDate = moment(dateRow[0].innerHTML, "MMM DD, YYYY").format(); // select date from 4th column in table
            dateRow[0].setAttribute('data-order', realDate);
        });


        // Init datatable --- more info on datatables: https://datatables.net/manual/
        datatable = $(table).DataTable({
            "info": false,
            'order': [],
            'pageLength': 10,
        });
    }
     $(document).ready(function() {
    $('.checkPrev').on('submit', function(e) {
    e.preventDefault();
    $.ajax({
      url: request()+'?f=procedure&s=check',
      method: 'POST',
      data: $(this).serialize(),
      beforeSend: function(){
      },
      success : function(response){
       console.log(response)
        if (response.status == 200) {
                        Swal.fire({
                            text: response.message,
                            icon: "success",
                            buttonsStyling: !1,
                            confirmButtonText: "Redirecting You",
                            customClass: {
                                confirmButton: "btn btn-primary"
                            }
                        });
                        setTimeout(function() {
                            window.location.href = response.url;
                        }, 2e3);
                    } else {
                        Swal.fire({
                            text: response.message,
                            icon: "warning",
                            buttonsStyling: !1,
                            confirmButtonText: "Try Again!",
                            customClass: {
                                confirmButton: "btn btn-danger"
                            }
                        });
                    }
      }
    })
  });
  });

    // Init daterangepicker
    var initDaterangepicker = () => {
        var start = moment().subtract(29, "days");
        var end = moment();
        var input = $("#kt_ecommerce_report_sales_daterangepicker");

        function cb(start, end) {
            input.html(start.format("MMMM D, YYYY") + " - " + end.format("MMMM D, YYYY"));
        }

        input.daterangepicker({
            startDate: start,
            endDate: end,
            ranges: {
                "Today": [moment(), moment()],
                "Yesterday": [moment().subtract(1, "days"), moment().subtract(1, "days")],
                "Last 7 Days": [moment().subtract(6, "days"), moment()],
                "Last 30 Days": [moment().subtract(29, "days"), moment()],
                "This Month": [moment().startOf("month"), moment().endOf("month")],
                "Last Month": [moment().subtract(1, "month").startOf("month"), moment().subtract(1, "month").endOf("month")]
            }
        }, cb);

        cb(start, end);
    }

    // Hook export buttons
    var exportButtons = () => {
        const documentTitle = "<?=  $sbs['bss']['b_name']." \' ".$report ?>";
        var buttons = new $.fn.dataTable.Buttons(table, {
            buttons: [
                {
                    extend: 'copyHtml5',
                    title: documentTitle
                },
                {
                    extend: 'excelHtml5',
                    title: documentTitle
                },
                {
                    extend: 'csvHtml5',
                    title: documentTitle
                },
                {
                    extend: 'pdfHtml5',
                    title: documentTitle
                }
            ]
        }).container().appendTo($('#kt_ecommerce_report_sales_export'));

        // Hook dropdown menu click event to datatable export buttons
        const exportButtons = document.querySelectorAll('#kt_ecommerce_report_sales_export_menu [data-kt-ecommerce-export]');
        exportButtons.forEach(exportButton => {
            exportButton.addEventListener('click', e => {
                e.preventDefault();

                // Get clicked export value
                const exportValue = e.target.getAttribute('data-kt-ecommerce-export');
                const target = document.querySelector('.dt-buttons .buttons-' + exportValue);

                // Trigger click event on hidden datatable export buttons
                target.click();
            });
        });
    }


    // Search Datatable --- official docs reference: https://datatables.net/reference/api/search()
    var handleSearchDatatable = () => {
        const filterSearch = document.querySelector('[data-kt-ecommerce-order-filter="search"]');
        filterSearch.addEventListener('keyup', function (e) {
            datatable.search(e.target.value).draw();
        });
    }

    // Public methods
    return {
        init: function () {
            table = document.querySelector('#kt_ecommerce_report_sales_table');

            if (!table) {
                return;
            }

            initDatatable();
            initDaterangepicker();
            exportButtons();
            handleSearchDatatable();
        }
    };
}();

// On document ready
KTUtil.onDOMContentLoaded(function () {
    KTAppEcommerceReportSales.init();
});

</script>