<?php
$products = get_data("items", "WHERE i_business_id = '" . $sbs['bss']['business_id'] . "'");
?>
 <!--begin::Content-->
                <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
                    <!--begin::Container-->
                    <div class="container-xxl" id="kt_content_container">
                        <!--begin::Products-->
                        <div class="card card-flush">
                            <!--begin::Card header-->
                            <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                                <!--begin::Card title-->
                                <div class="card-title">
                                    <!--begin::Search-->
                                    <div class="d-flex align-items-center position-relative my-1">
                                        <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                                        <span class="svg-icon svg-icon-1 position-absolute ms-4">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                                                <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
                                            </svg>
                                        </span>
                                        <!--end::Svg Icon-->
                                        <input type="text" data-kt-ecommerce-order-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Search Product" />
                                    </div>
                                    <!--end::Search-->
                                </div>
                                <!--end::Card title-->
                                <!--begin::Card toolbar-->

                                <!--end::Card toolbar-->
                            </div>
                            <!--end::Card header-->
                            <!--begin::Card body-->
                            <div class="card-body pt-0">
                                <!--begin::Table-->
                                <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_ecommerce_sales_table">
                                    <!--begin::Table head-->
                                    <thead>
                                        <!--begin::Table row-->
                                        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">

                                            <th class="min-w-20px">S/No.</th>
                                            <th class="min-w-100px">Product</th>
                                            <th class="min-w-100px">Units</th>
                                            <th class="min-w-70px">Category</th>
                                            <th class="min-w-70px">Brand</th>
                                            <!-- <th class="min-w-100px">Buying Price</th> -->
                                            <th class="min-w-100px">Selling Price</th>
                                            <th class="text-end min-w-100px">Date Added</th>
                                            <th class="text-end min-w-100px">Date Updated</th>
                                            <!-- <th class="text-end min-w-100px">Actions</th> -->
                                        </tr>
                                        <!--end::Table row-->
                                    </thead>
                                    <!--end::Table head-->
                                    <!--begin::Table body-->
                                    <tbody class="fw-bold text-gray-600">
                                        <!--begin::Table row-->
                                        <?php
                                        $num = 0;
                                        foreach ($products as $product) :
                                            $cat_data = getOneItem("categories", "c_business_id", $sbs['bss']['business_id'], "category_id", $product['i_category_id']);
                                            $brand_data = getOneItem("brand", "b_business_id", $sbs['bss']['business_id'], "brand_id", $product['i_brand_id']);
                                        ?>
                                            <tr>
                                                <!--begin::Checkbox-->
                                                <td><?= $num += 1 ?></td>
                                                <!--end::Checkbox-->
                                                <!--begin::Customer=-->
                                                <td><?= $product['item_name'] ?></td>
                                                <!--end::Customer=-->
                                                <td><?= $product['units'] ?></td>
                                                <!--begin::Status=-->
                                                <td><?= $cat_data['c_name'] ?></td>
                                                <td><?= $brand_data['brand_name'] ?></td>
                                                <!--end::Status=-->
                                                <!--begin::Order ID=-->
                                              <!--  -->
                                                <!--end::Order ID=-->
                                                <!--begin::Total=-->
                                                <td class=" pe-0">
                                                    <span class="fw-bolder">UGX: <?= number_format($product['item_price'], 0, '', ',') ?></span>
                                                </td>
                                                <!--end::Total=-->
                                                <!--begin::Date Added=-->
                                                <td class="text-end" data-order="2022-05-31">
                                                    <span class="fw-bolder"><?= $product['i_craeted'] ?></span>
                                                </td>
                                                 <td class="text-end" data-order="2022-05-31">
                                                    <span class="fw-bolder"><?= $product['i_updated'] ?></span>
                                                </td>
                                                <!--end::Date Added=-->


                                            </tr>
                                        <?php endforeach; ?>
                                        <!--end::Table row-->


                                    </tbody>
                                    <!--end::Table body-->
                                </table>
                                <!--end::Table-->
                            </div>
                            <!--end::Card body-->
                        </div>
                        <!--end::Products-->
                    </div>
                    <!--end::Container-->
                </div>
                <!--end::Content-->