  <?php
$todayTime = getCurrentDateOnly();
$day1 = $todayTime . ' 00:00:00';
$day2 = $todayTime . ' 23:59:59';
$day1 = $_GET['day1'];
$day2 = $_GET['day2'];
$report_type = $_GET['r'];
if ($report_type == 's' || $report_type == 'g') {
    $report =  "Sales Report";
    if ($report_type == 'g') {
        $report =  "General Report";
    }
    $orders = getSalesBetweenDaysByCashier($day1, $day2, $sbs['bss']['business_id'], $sbs['user']['user_id']);
    $totalSales = 'Total Sales = UGX : ' . getTotalSalesBetweenDaysByCashier($day1, $day2, $sbs['bss']['business_id'], $sbs['user']['user_id'])['total_sales'];
} elseif ($report_type == 'c') {
    $report =  "Credits Report";
    $orders = getCreditSalesBetweenDaysByCashier($day1, $day2, $sbs['bss']['business_id'], $sbs['user']['user_id']);
    $totalSales = 'Total Credits = UGX : ' . getTotalSalesBetweenDaysByCashier($day1, $day2, $sbs['bss']['business_id'], $sbs['user']['user_id'])['total_cr'];
} else if ($report_type == 'e') {
}

// $orders = getTodaysData("my_orders", "o_business_id", $sbs['bss']['business_id'], "created", getCurrentDateOnly());

$page = "Reports";
?>
  <!--begin::Content-->
                <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
                    <!--begin::Container-->
                    <div class="container-xxl" id="kt_content_container">

                        <div class="text-center mb-18">
                            <!--begin::Title-->
                            <h3 class="fs-2hx text-dark mb-6"><?= $sbs['bss']['b_name'] ?></h3>
                            <!--end::Title-->
                            <!--begin::Text-->
                            <div class="fs-5 text-dark fw-bold"><?= $sbs['user']['firstname'] . " " . $sbs['user']['lastname'] . '( Cashier )' ?><br /><?= $report ?>
                                <br /><?= 'From ' . date('Y-m-d g:iA', strtotime($day1)) . ' To ' . date('Y-m-d g:iA', strtotime($day2)) . '<br />' . $totalSales ?><br />
                            </div>
                            <!--end::Text-->

                        </div>
                        <!--begin::Products-->
                        <div class="card card-flush">
                            <!--begin::Card header-->
                            <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                                <!--begin::Card title-->
                                <div class="card-title">
                                    <!--begin::Search-->
                                    <div class="d-flex align-items-center position-relative my-1">
                                        <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                                        <span class="svg-icon svg-icon-1 position-absolute ms-4">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                                                <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
                                            </svg>
                                        </span>
                                        <!--end::Svg Icon-->
                                        <input type="text" data-kt-ecommerce-order-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Search Report" />
                                    </div>
                                    <!--end::Search-->
                                    <!--begin::Export buttons-->
                                    <div id="kt_ecommerce_report_sales_export" class="d-none"></div>
                                    <!--end::Export buttons-->
                                </div>
                                <!--end::Card title-->
                                <!--begin::Card toolbar-->
                                <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
                                    <!--begin::Daterangepicker-->

                                    <!--end::Daterangepicker-->
                                    <!--begin::Export dropdown-->
                                    <button type="button" class="btn btn-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
                                        <!--begin::Svg Icon | path: icons/duotune/arrows/arr078.svg-->
                                        <span class="svg-icon svg-icon-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                <rect opacity="0.3" x="12.75" y="4.25" width="12" height="2" rx="1" transform="rotate(90 12.75 4.25)" fill="currentColor" />
                                                <path d="M12.0573 6.11875L13.5203 7.87435C13.9121 8.34457 14.6232 8.37683 15.056 7.94401C15.4457 7.5543 15.4641 6.92836 15.0979 6.51643L12.4974 3.59084C12.0996 3.14332 11.4004 3.14332 11.0026 3.59084L8.40206 6.51643C8.0359 6.92836 8.0543 7.5543 8.44401 7.94401C8.87683 8.37683 9.58785 8.34458 9.9797 7.87435L11.4427 6.11875C11.6026 5.92684 11.8974 5.92684 12.0573 6.11875Z" fill="currentColor" />
                                                <path d="M18.75 8.25H17.75C17.1977 8.25 16.75 8.69772 16.75 9.25C16.75 9.80228 17.1977 10.25 17.75 10.25C18.3023 10.25 18.75 10.6977 18.75 11.25V18.25C18.75 18.8023 18.3023 19.25 17.75 19.25H5.75C5.19772 19.25 4.75 18.8023 4.75 18.25V11.25C4.75 10.6977 5.19771 10.25 5.75 10.25C6.30229 10.25 6.75 9.80228 6.75 9.25C6.75 8.69772 6.30229 8.25 5.75 8.25H4.75C3.64543 8.25 2.75 9.14543 2.75 10.25V19.25C2.75 20.3546 3.64543 21.25 4.75 21.25H18.75C19.8546 21.25 20.75 20.3546 20.75 19.25V10.25C20.75 9.14543 19.8546 8.25 18.75 8.25Z" fill="#C4C4C4" />
                                            </svg>
                                        </span>
                                        <!--end::Svg Icon-->Export Report
                                    </button>
                                    <!--begin::Menu-->
                                    <div id="kt_ecommerce_report_sales_export_menu" class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-200px py-4" data-kt-menu="true">
                                        <!--begin::Menu item-->
                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3" data-kt-ecommerce-export="copy">Copy to clipboard</a>
                                        </div>
                                        <!--end::Menu item-->
                                        <!--begin::Menu item-->
                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3" data-kt-ecommerce-export="excel">Export as Excel</a>
                                        </div>
                                        <!--end::Menu item-->
                                        <!--begin::Menu item-->
                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3" data-kt-ecommerce-export="csv">Export as CSV</a>
                                        </div>
                                        <!--end::Menu item-->
                                        <!--begin::Menu item-->
                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3" data-kt-ecommerce-export="pdf">Export as PDF</a>
                                        </div>
                                        <!--end::Menu item-->
                                    </div>
                                    <!--end::Menu-->
                                    <!--end::Export dropdown-->
                                </div>
                                <!--end::Card toolbar-->
                            </div>
                            <!--end::Card header-->
                            <!--begin::Card body-->
                            <div class="card-body pt-0">
                                <?php if ($report_type == 's' || $report_type == 'c' || $report_type == 'g') { ?>
                                    <!--begin: sales or credits :Table-->
                                    <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_ecommerce_report_sales_table">
                                        <!--begin::Table head-->
                                        <thead>
                                            <!--begin::Table row-->
                                            <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                                                <th class="min-w-10px">S/No.</th>
                                                <th class="min-w-50px">Date</th>
                                                <th class="min-w-50px">Product Name</th>
                                                <th class=" min-w-50px">Products Sold</th>
                                                <th class="min-w-50px">Unit Price</th>
                                                <th class="min-w-50px">Total</th>
                                            </tr>
                                            <!--end::Table row-->
                                        </thead>
                                        <!--end::Table head-->
                                        <!--begin::Table body-->
                                        <tbody class="fw-bold text-gray-600">
                                            <!--begin::Table row-->
                                            <?php
                                            $num = 0;
                                            foreach ($orders as $order) :
                                                $itemData = single_item("items", "WHERE item_id = '" . $order['item_id'] . "'");
                                            ?>
                                                <tr>
                                                    <td><?= $num += 1 ?></td>
                                                    <!--begin::Date=-->
                                                    <td><?= $order['created'] ?></td>
                                                    <!--end::Date=-->
                                                    <!--begin::No Orders=-->
                                                    <td class="pe-0"><?= $itemData['item_name'] ?></td>
                                                    <!--end::No Orders=-->
                                                    <!--begin::Products sold=-->
                                                    <td class="pe-0"><?= $order['quantity'] . ' ' . $itemData['units'] ?></td>
                                                    <!--end::Products sold=-->
                                                    <!--begin::Tax=-->
                                                    <td class="pe-0">UGX: <?= number_format($itemData['item_price'], 0, '', ','); ?></td>
                                                    <!--end::Tax=-->
                                                    <!--begin::Total=-->
                                                    <td class="">UGX: <?= number_format($itemData['item_price'] * $order['quantity'], 0, '', ','); ?></td>
                                                    <!--end::Total=-->
                                                </tr>
                                            <?php endforeach; ?>
                                            <!--end::Table row-->

                                            <!--end::Table row-->



                                        </tbody>
                                        <!--end::Table body-->
                                    </table>
                                    <!--end: sales or credits:Table-->
                                <?php } else if ($report_type == 'e') { ?>
                                    <!--begin: exp :Table-->
                                    <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_ecommerce_report_sales_table">
                                        <!--begin::Table head-->
                                        <thead>
                                            <!--begin::Table row-->
                                            <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                                                <th class="min-w-10px">S/No.</th>
                                                <th class="min-w-50px">Date</th>
                                                <th class="min-w-50px">Expense Name</th>
                                                <th class=" min-w-100px">Description</th>
                                                <th class="min-w-50px">Amount</th>
                                            </tr>
                                            <!--end::Table row-->
                                        </thead>
                                        <!--end::Table head-->
                                        <!--begin::Table body-->
                                        <tbody class="fw-bold text-gray-600">
                                            <!--begin::Table row-->
                                            <?php
                                            $num = 0;
                                            foreach ($exps as $exp) :
                                                $itemData = single_item("items", "WHERE item_id = '" . $order['item_id'] . "'");
                                            ?>
                                                <tr>
                                                    <td><?= $num += 1 ?></td>
                                                    <!--begin::Date=-->
                                                    <td><?= $exp['created'] ?></td>
                                                    <!--end::Date=-->
                                                    <!--begin::No Orders=-->
                                                    <td class="pe-0"><?= $exp['name'] ?></td>
                                                    <!--end::No Orders=-->
                                                    <!--begin::Products sold=-->
                                                    <td class="pe-0"><?= $exp['description'] ?></td>
                                                    <!--end::Products sold=-->

                                                    <!--begin::Total=-->
                                                    <td class="">UGX: <?= number_format($exp['amount'], 0, '', ','); ?></td>
                                                    <!--end::Total=-->
                                                </tr>
                                            <?php endforeach; ?>
                                            <!--end::Table row-->

                                            <!--end::Table row-->



                                        </tbody>
                                        <!--end::Table body-->
                                    </table>
                                    <!--end: exp:Table-->
                                <?php } ?>
                            </div>
                            <!--end::Card body-->
                        </div>
                        <!--end::Products-->



                    </div>
                    <!--end::Container-->
                </div>
                <!--end::Content-->

                