
<!DOCTYPE html>
<!--
Author: Keneth Kansiime , Kiiza Trevour , Oketch Edward
Product Name: Stock Balancing System (SBS) 
Website: http://www.keenthemes.com
Contact: kansiimekeneth4@gmail.com
Follow: https://twitter.com/stock_sbs
Like: www.facebook.com/keenthemes
-->
<html lang="en">
<!--begin::Head-->

<head>
	<title>Register Business | SBS</title>
	<meta charset="utf-8" />
	 <meta name="description" content="Stock Balancing System (SBS). Enables users to manage their businesses through monitoring stock, determining business performance statistics such as sales, profits, losses , credits, expenses in addition to generating daily, weekly, monthly and annual balancing reports." />
	<meta name="keywords" content="Stock Balancing System, SBS, Know Your Business performance , Sales, Profits, losses , reports, stock, stock balancing system, sbs, credits , business , monitor your business , monitor your cashiers, cashiers , track your sales, track your profits, track your expenses, track your credits, Know Your losses, business performance" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta property="og:locale" content="en_US" />
	<meta property="og:type" content="article" />
	<meta property="og:title" content="Stock Balancing System, SBS, Know Your Business performance" />
	<meta property="og:url" content="https://keenthemes.com/metronic" />
	<meta property="og:site_name" content="Stock Balancing System | SBS" />
	<link rel="canonical" href="https://preview.keenthemes.com/metronic8" />
	<link rel="shortcut icon" href="assets/logo/SBS-b.png" />
	<!--begin::Fonts-->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
	<!--end::Fonts-->
	<!--begin::Page Vendor Stylesheets(used by this page)-->
	<link href="assets/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
	<link href="assets/plugins/custom/vis-timeline/vis-timeline.bundle.css" rel="stylesheet" type="text/css" />
	<!--end::Page Vendor Stylesheets-->
	<!--begin::Global Stylesheets Bundle(used by all pages)-->
	<link href="assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
	<link href="assets/css/style.bundle.css" rel="stylesheet" type="text/css" />
	<!--end::Global Stylesheets Bundle-->
	<!--Begin::Google Tag Manager -->
	<script>
		(function(w, d, s, l, i) {
			w[l] = w[l] || [];
			w[l].push({
				'gtm.start': new Date().getTime(),
				event: 'gtm.js'
			});
			var f = d.getElementsByTagName(s)[0],
				j = d.createElement(s),
				dl = l != 'dataLayer' ? '&amp;l=' + l : '';
			j.async = true;
			j.src = '../../../www.googletagmanager.com/gtm5445.html?id=' + i + dl;
			f.parentNode.insertBefore(j, f);
		})(window, document, 'script', 'dataLayer', 'GTM-5FS8GGP');
	</script>
	<!--End::Google Tag Manager -->
</head>
<!--end::Head-->
<!--begin::Body-->

<body id="kt_body" class="bg-body">
	<!--Begin::Google Tag Manager (noscript) -->
	<noscript>
		<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5FS8GGP" height="0" width="0" style="display:none;visibility:hidden"></iframe>
	</noscript>
	<!--End::Google Tag Manager (noscript) -->
	<!--begin::Main-->
	<!--begin::Root-->
	<div class="d-flex flex-column flex-root">
		<!--begin::Authentication - Sign-up -->
		<div class="d-flex flex-column flex-lg-row flex-column-fluid">
			<!--begin::Aside-->
			<div class="d-flex flex-column flex-lg-row-auto w-xl-600px positon-xl-relative" style="background-color: #F2C98A">
				<!--begin::Wrapper-->
				<div class="d-flex flex-column position-xl-fixed top-0 bottom-0 w-xl-600px scroll-y">
					<!--begin::Content-->
					<div class="d-flex flex-row-fluid flex-column text-center p-10 pt-lg-20">
						<!--begin::Logo-->
						<a href="sbs" class="py-9 mb-5">
							<img alt="SBS Logo" src="<?= $sbs['config']['site_url'] ?>layout/assets/logo/SBS-b.png" class="h-200px" />
						</a>

						<!--end::Logo-->
						<!--begin::Title-->
						<h1 class="fw-bolder fs-2qx pb-5 pb-md-10" style="color: #986923;">Welcome to SBS</h1>
						<!--end::Title-->
						<!--begin::Description-->
						<p class="fw-bold fs-2" style="color: #986923;">Register Your Bisness Now
							<br />Keep Track of your stock in real-time
						</p>
						<!--end::Description-->
					</div>
					<!--end::Content-->
					<!--begin::Illustration-->
					<div class="d-flex flex-row-auto bgi-no-repeat bgi-position-x-center bgi-size-contain bgi-position-y-bottom min-h-100px min-h-lg-350px" style="background-image: url(<?= $sbs['config']['site_url'] ?>layout/assets/images/13.png)"></div>
					<!--end::Illustration-->
				</div>
				<!--end::Wrapper-->
			</div>
			<!--end::Aside-->
			<!--begin::Body-->
			<div class="d-flex flex-column flex-lg-row-fluid py-10">
				<!--begin::Content-->
				<div class="d-flex flex-center flex-column flex-column-fluid">
					<!--begin::Wrapper-->
					<div class="w-lg-600px p-10 p-lg-15 mx-auto">
						<!--begin::Form-->
						<form id="bss" enctype="multipart/form-data" class="form-control" novalidate="novalidate">
							<!--begin::Heading-->
							<div class="mb-10 text-center">
								<!--begin::Title-->
								<h1 class="text-dark mb-3">Register Business</h1>
								
							</div>
							<!--end::Heading-->

							<!--begin::Separator-->
							<div class="d-flex align-items-center mb-10">
								<div class="border-bottom border-gray-300 mw-50 w-100"></div>
								<span class="fw-bold text-gray-400 fs-7 mx-2">SBS</span>
								<div class="border-bottom border-gray-300 mw-50 w-100"></div>
							</div>
							<!--end::Separator-->
							<div class="fv-row mb-7">
								<label class="form-label fw-bolder text-dark fs-6">Business Name</label>
								<input class="form-control form-control-lg form-control-solid" type="email" placeholder="" name="bnss_name" autocomplete="off" />
							</div>
							<div class="fv-row mb-7">
								<label class="form-label fw-bolder text-dark fs-6">Address</label>
								<input class="form-control form-control-lg form-control-solid" type="email" placeholder="" name="address" autocomplete="off" />
							</div>

							<!--end::Input group-->
							<!--begin::Input group-->


							<div class="fv-row fv-plugins-icon-container">
								<!--begin::Label-->
								<label class="required form-label">Business Type</label>
								<!--end::Label-->
								<!--begin::Select2-->
								<select name="b_type" class="form-select mb-2 select2-hidden-accessible" data-control="select2" data-hide-search="true" data-placeholder="Select an option" name="payment_method" id="kt_ecommerce_edit_order_payment" data-select2-id="select2-data-kt_ecommerce_edit_order_payment" tabindex="-1" aria-hidden="true">
									<option value="B" selected="selected" data-select2-id="select2-data-8-aggh">Choose Business Type</option>
									<?php foreach ($db->get('business_type') as $key => $value): ?>
									<option value="<?=$value->id?>"><?=$value->title?></option>
									<?php endforeach;?>
						
								</select>


								<!--end::Select2-->
								<!--begin::Description-->
								<div class="text-muted fs-7">Set payment status.</div>
								<!--end::Description-->
								<div class="fv-plugins-message-container invalid-feedback"></div>
							</div>
							<!--end::Input group-->
							<!--begin::Input group-->
							<div class="fv-row mb-7">
								<label class="form-label fw-bolder text-dark fs-6">Website</label>
								<input class="form-control form-control-lg form-control-solid" type="email" placeholder="" name="website" autocomplete="off" />
							</div>
							<!--end::Input group-->

							<!--begin::Input group-->
							<div class="fv-row mb-10">
								<label class="form-check form-check-custom form-check-solid form-check-inline">
									<input class="form-check-input" type="checkbox" name="toc" value="1" />
									<span class="form-check-label fw-bold text-gray-700 fs-6">I Agree
										<a href="#" class="ms-1 link-primary">Terms and conditions</a>.</span>
								</label>
							</div>
							<!--end::Input group-->
							<!--begin::Actions-->
							<div class="text-center">
								<button type="submit" name="submit" id="kt_sign_up_submit" class="btn btn-lg btn-primary">
									<span class="indicator-label">Register Business</span>
									<span class="indicator-progress">Please wait...
										<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
								</button>
							</div>
							<!--end::Actions-->
						</form>
						<!--end::Form-->
					</div>
					<!--end::Wrapper-->
				</div>
				<!--end::Content-->
				<!--begin::Footer-->
				<div class="d-flex flex-center flex-wrap fs-6 p-5 pb-0">
					<!--begin::Links-->
					<div class="d-flex flex-center fw-bold fs-6">
						<a href="#" class="text-muted text-hover-primary px-2" target="_blank">About</a>
						<a href="#" class="text-muted text-hover-primary px-2" target="_blank">Support</a>
					</div>
					<!--end::Links-->
				</div>
				<!--end::Footer-->
			</div>
			<!--end::Body-->
		</div>
		<!--end::Authentication - Sign-up-->
	</div>
	<!--end::Root-->
	<!--end::Main-->
	<!--begin::Javascript-->
	<script>
		var hostUrl = "assets/index.html";
	</script>
	<!--begin::Global Javascript Bundle(used by all pages)-->
	<script src="assets/plugins/global/plugins.bundle.js"></script>
	<script src="assets/js/scripts.bundle.js"></script>
	<!--end::Global Javascript Bundle-->
	<!--begin::Page Vendors Javascript(used by this page)-->
	<script src="assets/plugins/custom/datatables/datatables.bundle.js"></script>
	<script src="assets/plugins/custom/formrepeater/formrepeater.bundle.js"></script>
	<!--end::Page Vendors Javascript-->
	<!--begin::Page Custom Javascript(used by this page)-->
	<script src="assets/js/custom/apps/ecommerce/sales/save-order.js"></script>
	<script src="assets/js/widgets.bundle.js"></script>
	<script src="assets/js/custom/widgets.js"></script>
	<script src="assets/js/custom/apps/chat/chat.js"></script>
	<script src="assets/js/custom/intro.js"></script>
	<script src="assets/js/custom/utilities/modals/upgrade-plan.js"></script>
	<script src="assets/js/custom/utilities/modals/users-search.js"></script>
	<!--end::Page Custom Javascript-->
	<!--end::Javascript-->
</body>
<!--end::Body-->

</html>
<script type="text/javascript">
	$(document).ready(function() {
		$('#bss').on('submit', function(e) {
			e.preventDefault();
			$.ajax({
				url: request()+'?f=auth&s=bss',
				method: 'POST',
				data: $(this).serialize(),
				beforesend: function() {

				},
				success: function(response) {
					console.log(response);
					//e.removeAttribute("data-kt-indicator");

					if (response.status == 200) {
						Swal.fire({
							text: response.message,
							icon: "success",
							buttonsStyling: !1,
							confirmButtonText: "Redirecting You",
							customClass: {
								confirmButton: "btn btn-primary"
							}
						});
						setTimeout(function() {
							window.location.href = response.url;
						}, 2e3);
					} else {
						Swal.fire({
							text: response.message,
							icon: "warning",
							buttonsStyling: !1,
							confirmButtonText: "Try Again!",
							customClass: {
								confirmButton: "btn btn-danger"
							}
						});
					}
				}
			});
		});

	})
</script>