<div class="engage-toolbar d-flex position-fixed px-5 fw-bolder zindex-2 top-50 end-0 transform-90 mt-20 gap-2">
    <!--begin::Demos drawer toggle-->
   
    <!--end::Demos drawer toggle-->
    <!--begin::Help drawer toggle-->
    <button id="kt_help_toggle" class="engage-help-toggle btn btn-flex h-35px bg-body btn-color-gray-700 btn-active-color-gray-900 shadow-sm px-5 rounded-top-0" title="Get Help From Our Team" data-bs-toggle="tooltip" data-bs-placement="left" data-bs-dismiss="click" data-bs-trigger="hover">Help</button>
    <!--end::Help drawer toggle-->
    <!--begin::Purchase link-->
    
    <!--end::Purchase link-->
</div>